### ISSUE TITLE
Code for Canada YVR

### ISSUE THREAD

**Issue by ogryzek** [codeforcanada/codeforcanada.org#3]
Can we update the [Code for Canada Vancouver](https://www.codeforamerica.org/brigade/Code-for-Vancouver/) links to maybe point to Code for Canada Vancouver things?  
  
Here's the [Meetup page](http://www.meetup.com/Code-for-Canada-Vancouver/) and the [GitHub organization](https://github.com/CodeForCanadaYVR).

**Comment by nvk** [comment]
I don't control https://www.codeforamerica.org/brigade/Code-for-Vancouver

**Comment by patcon** [comment]
@ogryzek I think someone central added that to the map, but you can submit PR here:
https://github.com/codeforamerica/brigade-information/blame/master/organizations.json#L1114

**Comment by ogryzek** [comment]
Great, thank you :)

*- <**[) r 3 \/\*/> -
Favorites of the Month
blog
<http://nicholasjackson.github.io/microservices/go/building-and-testing-microservices-part1/>
 | song <https://summerheart.bandcamp.com/album/pretty-haze-single> | book
<http://intermezzos.github.io/book/> | etc <http://shoesrb.com/>
